[package]
name = "beacon_hook_bypass_memscan"
version = "0.1.0"
edition = "2018"

[dependencies]
detour = "0.8.0"
lazy_static = "1.4.0"
region = "3.0.0"
winapi = { version = "0.3.9", features = ["errhandlingapi", "libloaderapi", "synchapi", "winbase"] }
